### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by zhengruyi** [stoqs/stoqs#846]
Hello ,  I met some problem when i tried to install stoqs on my mac (MacOS Mojave 10.14.3 ,vargant 2.2.3  and virtual box 6.0.4),  i  found some errors "cannot reconstruct rpm from disk files ".  after it has finished installation,  when i run command "cd $STOQS_HOME && source venv-stoqs/bin/activate",  it  returns a error "-bash: venv-stoqs/bin/activate: No such file or directory", when i run the command "./test.sh CHANGEME load noextraload" , it returns a error "CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
ALTER DATABASE
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Cannot migrate default database; refer to above error message."

please help me!!!

**Comment by MBARIMike** [comment]
It appears that Vagrant's provisioning step failed. I suggest capturing its output and looking in the `provision.out` file for the reason why, e.g.:

```
vagrant up --provider virtualbox | tee provision.out
```
I also suggest looking through the discussion in https://github.com/stoqs/stoqs/issues/306.

**Comment by zhengruyi** [comment]
> It appears that Vagrant's provisioning step failed. I suggest capturing its output and looking in the `provision.out` file for the reason why, e.g.:
> 
> ```
> vagrant up --provider virtualbox | tee provision.out
> ```
> I also suggest looking through the discussion in #306.



> It appears that Vagrant's provisioning step failed. I suggest capturing its output and looking in the `provision.out` file for the reason why, e.g.:
> 
> ```
> vagrant up --provider virtualbox | tee provision.out
> ```
> I also suggest looking through the discussion in #306.

Thank you for your answer , I ran  the command and  upload the file . I   don't understand where is the problem, can you help me ? 
[provision.out.zip](https://github.com/stoqs/stoqs/files/2920942/provision.out.zip)

**Comment by zhengruyi** [comment]
hello ?   Can anyone  help me ?  my project have to use this software, please help me .

**Comment by MBARIMike** [comment]
I suggest starting at the end of your provision.out file and looking back for the source of the error.

**Comment by zhengruyi** [comment]
good night ! I ran the command at end of file, here is the result:
zhengruyideMacBook-Pro:stoqsvm zhengruyi$ vagrant ssh -- -X
==> vagrant: A new version of Vagrant is available: 2.2.4 (installed version: 2.2.3)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

/usr/bin/xauth:  file /home/vagrant/.Xauthority does not exist
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[vagrant@localhost ~]$ export STOQS_HOME=/vagrant/dev/stoqsgit
[vagrant@localhost ~]$ cd /vagrant/dev/stoqsgit
[vagrant@localhost stoqsgit]$ export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5438/stoqs
[vagrant@localhost stoqsgit]$ ./test.sh CHANGEME load noextraload
CREATE ROLE
CREATE ROLE
Loading standard data for unit and functional tests...
NOTICE:  database "stoqs" does not exist, skipping
DROP DATABASE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
ALTER DATABASE
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Cannot migrate default database; refer to above error message.
[vagrant@localhost stoqsgit]$


Can you give me some advices ?

**Comment by MBARIMike** [comment]
Maybe your system doesn't support NFS. Read the comments about NFS and make changes in your `provision.sh`. Then rebuild your VM, capturing the output:
```
vagrant destroy
vagrant up --provider virtualbox | tee provision.out
```

**Comment by zhengruyi** [comment]
hello,  according to your advice, i comment this line  "config.vm.synced_folder '.', '/vagrant', nfs: true,  mount_options: ['tcp', 'fsc' ,'actimeo=300']" in Vagrantile and changer the path from "/vagrant/dev/stoqsgit" to "/home/vagrant/dev/stoqsgit".  I am  waiting the result.

**Comment by zhengruyi** [comment]
I met the same problem even if i make changes in these files,

zhengruyideMacBook-Pro:stoqsvm zhengruyi$ vagrant ssh -- -X
/usr/bin/xauth:  file /home/vagrant/.Xauthority does not exist
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[vagrant@localhost ~]$ export STOQS_HOME=/home/vagrant/dev/stoqsgit
[vagrant@localhost ~]$ cd /home/vagrant/dev/stoqsgit
[vagrant@localhost stoqsgit]$ export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5438/stoqs
[vagrant@localhost stoqsgit]$ ./test.sh CHANGEME load noextraload
CREATE ROLE
CREATE ROLE
Loading standard data for unit and functional tests...
NOTICE:  database "stoqs" does not exist, skipping
DROP DATABASE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
ALTER DATABASE
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Cannot migrate default database; refer to above error message.

this is the provision.out:
[provision.out_NoNFSzip.zip](https://github.com/stoqs/stoqs/files/2930352/provision.out_NoNFSzip.zip)

**Comment by zhengruyi** [comment]
Do you have any idea ?  I think  it isn't the problem of NFS system.

**Comment by zhengruyi** [comment]
I found something in the file, like this :  
 default: cannot reconstruct rpm from disk files
 default: Some delta RPMs failed to download or rebuild. Retrying..

is it the reason?

**Comment by MBARIMike** [comment]
It seems that the error message of importance in your provision.out is this one:
```
    default: /tmp/vagrant-shell: line 303: cd: stoqsgit: No such file or directory
```
Which is caused by [this line in provision.sh](https://github.com/stoqs/stoqs/blob/04e1fd9f326752bc119585b2a59aa7be67562a65/provision.sh#L303).

**Comment by MBARIMike** [comment]
This is [the fix](https://github.com/stoqs/stoqs/commit/badf166c60e3d6561f2c62376fb4b57edffa8568) for that problem on line 303.

**Comment by zhengruyi** [comment]
unfortunately , I met the same problem, it doesn't work .

zhengruyideMacBook-Pro:stoqsvm zhengruyi$ vagrant ssh -- -X
/usr/bin/xauth:  file /home/vagrant/.Xauthority does not exist
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[vagrant@localhost ~]$ export STOQS_HOME=/vagrant/dev/stoqsgit
[vagrant@localhost ~]$ cd /vagrant/dev/stoqsgit
[vagrant@localhost stoqsgit]$ export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5438/stoqs
[vagrant@localhost stoqsgit]$ ./test.sh CHANGEME load noextraload
CREATE ROLE
CREATE ROLE
Loading standard data for unit and functional tests...
NOTICE:  database "stoqs" does not exist, skipping
DROP DATABASE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
ALTER DATABASE
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Cannot migrate default database; refer to above error message.

**Comment by zhengruyi** [comment]
this  is the file
[Uploading provision.sh.zip…]()

**Comment by MBARIMike** [comment]
I suggest doing a clean install, e.g.:
```
export STOQSVM=~/Vagrants/stoqsvm  # Assign to your directory
cd $STOQSVM
vagrant destroy
cd ~/
rm -r $STOQSVM
mkdir $STOQSVM
cd $STOQSVM
curl "https://raw.githubusercontent.com/stoqs/stoqs/master/Vagrantfile" -o Vagrantfile
curl "https://raw.githubusercontent.com/stoqs/stoqs/master/provision.sh" -o provision.sh
vagrant plugin install vagrant-vbguest
vagrant up --provider virtualbox | tee provision.out
```

**Comment by MBARIMike** [comment]
@zhengruyi Do you still have any problems with the installation?

**Comment by zhengruyi** [comment]
this is the problem :
[vagrant@localhost stoqsgit]$ ./test.sh CHANGEME load noextraload
Loading standard data for unit and functional tests...
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
Cannot create default database stoqs; refer to above message.
[vagrant@localhost stoqsgit]$

**Comment by MBARIMike** [comment]
It looks like your postgresql-10 server is not running. You can try starting it with:
```
sudo systemctl start postgresql-10
```
If you can't start it then check for any installation or startup errors in your `provision.out` file.

Also, I notice from your prompt that you are not in the Python virtualenv. Start it with:
```
cd $STOQS_HOME && source venv-stoqs/bin/activate
```
Your prompt should look like: `(venv-stoqs) [vagrant@localhost stoqsgit]$`.

**Comment by zhengruyi** [comment]
Thank you for your advice , but  I met another problem:
(venv-stoqs) [vagrant@localhost stoqsgit]$ ./test.sh CHANGEME load noextraload
Loading standard data for unit and functional tests...
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5438"?
Cannot create default database stoqs; refer to above message.
(venv-stoqs) [vagrant@localhost stoqsgit]$ pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
-bash: pg_ctl: command not found
(venv-stoqs) [vagrant@localhost stoqsgit]$ sudo systemctl start postgresql-10
Failed to start postgresql-10.service: Unit not found.


there is the file:
[provision.out.zip](https://github.com/stoqs/stoqs/files/2954427/provision.out.zip)

**Comment by MBARIMike** [comment]
It looks like a probable temporary network problem prevented the installation of Postgres:
```
    default: ================================================================================
    default:  Package                   Arch        Version                Repository   Size
    default: ================================================================================
    default: Installing for group install "PostgreSQL Database Server 10 PGDG":
    default:  postgresql10              x86_64      10.7-2PGDG.rhel7       pgdg10      1.6 M
    default:  postgresql10-contrib      x86_64      10.7-2PGDG.rhel7       pgdg10      591 k
    default:  postgresql10-libs         x86_64      10.7-2PGDG.rhel7       pgdg10      355 k
    default:  postgresql10-server       x86_64      10.7-2PGDG.rhel7       pgdg10      4.5 M
    default: Installing for dependencies:
    default:  libicu                    x86_64      50.1.2-17.el7          base        6.9 M
    default:  libxslt                   x86_64      1.1.28-5.el7           base        242 k
    default:
    default: Transaction Summary
    default: ================================================================================
    default: Install  4 Packages (+2 Dependent packages)
    default:
    default: Total download size: 14 M
    default: Installed size: 54 M
    default: Downloading packages:
    default: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/postgresql10-10.7-2PGDG.rhel7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: download.postgresql.org; Unknown error"
    default: Trying other mirror.
    default: http://mirrors.ircam.fr/pub/CentOS/7.6.1810/os/x86_64/Packages/libicu-50.1.2-17.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.ircam.fr; Unknown error"
    default: Trying other mirror.
    default: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/postgresql10-contrib-10.7-2PGDG.rhel7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: download.postgresql.org; Unknown error"
    default: Trying other mirror.
    default: http://mirrors.ircam.fr/pub/CentOS/7.6.1810/os/x86_64/Packages/libxslt-1.1.28-5.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.ircam.fr; Unknown error"
    default: Trying other mirror.
    default:
    default:
    default: Error downloading packages:
    default:   postgresql10-10.7-2PGDG.rhel7.x86_64: [Errno 256] No more mirrors to try.
    default:   postgresql10-contrib-10.7-2PGDG.rhel7.x86_64: [Errno 256] No more mirrors to try.
```
You can try executing the install again in your VM:
```
wget -q -N https://yum.postgresql.org/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
sudo rpm -ivh pgdg*
sudo yum groupinstall -y "Development Tools"
```
This will test whether Postgres can be installed, you'd still need to execute all the follow-on Postgres configuration done by provision.sh. If the test installation succeeds, then try re-provisioning your VM.
